### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Viresh-DL** [svishwa/crowdcount-mcnn#1]
Hello,
I was wondering if the ShahghaiTech crowd counting is publicly available ? 

Thanks

**Comment by svishwa** [comment]
Last time I checked, the dataset was not available publicly. You can write to the authors  - they can share the link.

**Comment by svishwa** [comment]
The dataset can be downloaded from here:
Dropbox:   https://www.dropbox.com/s/fipgjqxl7uj8hd5/ShanghaiTech.zip?dl=0
Baidu Disk: http://pan.baidu.com/s/1nuAYslz

**Comment by Viresh-R** [comment]
Thanks !!
