### ISSUE TITLE
What size of image should I use to get good performance

### ISSUE THREAD

**Issue by mrlzla** [svishwa/crowdcount-mcnn#10]
As I can see there is only conv layers and no fully connected (sure) so we could feed image of any size. I have no dataset you trained the model so my question is in topic ;) What sizes of image were used to train the model?

**Comment by svishwa** [comment]
I followed the training procedure explained in the original paper (https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Zhang_Single-Image_Crowd_Counting_CVPR_2016_paper.pdf). 

The training dataset was formed by cropping patches of size 1/4th the original image size from random locations. 

For inference, I used the test image of original resolution. Btw, the dataset links are now provided in the readme file.
