### ISSUE TITLE
Dataset required

### ISSUE THREAD

**Issue by asif07hossain** [svishwa/crowdcount-mcnn#11]
Dear,
You previously helped me with sending the Shanghaitech dataset. Now, I am need of Wroldexpo'10 dataset and UCSD dataset. 

Let me explain you a scenario about UCF_CC_50 dataset. I have 50 images. Now I put first 40 images in to train folder like shanghaitech, then rest 10 images i put on test folder. finally i got 359 formatted images to train my model. I want to know how authors tested their method with UCF_CC_50 dataset. 

Can you please reply me with these 3 queries. Thanks in advance.
asif07hossain@gmail.com is my gmail id

**Comment by asif07hossain** [comment]
Dear Concern,

Can you please provide me the UCF_CC_50, UCSD and Wroldexpo'10 dataset pre-processing codes to divide test and training?
my gmail id is: asif07hossain@gmail.com

**Comment by svishwa** [comment]
The pre-processing code provided for ShanghaiTech dataset can be modified for other datasets. Please follow the cross-validation split as discussed in the UCF_CC_50 dataset paper to perform the experiments.

**Comment by xxxwuwq** [comment]
> The pre-processing code provided for ShanghaiTech dataset can be modified for other datasets. Please follow the cross-validation split as discussed in the UCF_CC_50 dataset paper to perform the experiments.

the description about 5-fold cross-validation in paper, not specified the times about multiple 5-fold cross-validation.  As for current paper, it's unfair to compare the result on ucf_cc_50 for that there is no uniform standard(such as 5 times 5-fold cross validation, instead of once specified combination(handcraft))???
