### ISSUE TITLE
UCF_CC_50 data prepare

### ISSUE THREAD

**Issue by ChenyuGAO-CS** [svishwa/crowdcount-mcnn#12]
Dear svishwa, I don't know how to devided train and test dataset of UCF_CC_50, could you please provide me the UCF_CC_50 data prepare codes, if available?

**Comment by svishwa** [comment]
The pre-processing code provided for ShanghaiTech dataset can be modified for other datasets. Please follow the cross-validation split as discussed in the UCF_CC_50 dataset paper to perform the experiments.
