### ISSUE TITLE
relu

### ISSUE THREAD

**Issue by cryax** [svishwa/crowdcount-mcnn#15]
Hi svishwa,
I wonder why there're no relu layer in your model? (authors of "Single Image Crowd Counting via Multi Column Convolutional Neural Network" said that relu is adopted in their network.)

**Comment by svishwa** [comment]
Conv2d includes Conv layer + ReLU().  See the following definition of Conv2d in network.py

![image](https://user-images.githubusercontent.com/29029426/33492703-e199eee0-d68b-11e7-89f1-ebd67daf3488.png)
