### ISSUE TITLE
Issues,test.py

### ISSUE THREAD

**Issue by Dangwanli** [svishwa/crowdcount-mcnn#17]
When trying to run test.py I get the following message:
  File "C:\Users\GCZX\Desktop\crowdcount-mcnn-master\src\data_loader.py", line 35, in 
__init__
    img = cv2.resize(img,(wd_1,ht_1))

TypeError: integer argument expected, got float

**Comment by svishwa** [comment]
I am not really sure why this occurs, since wd_1 and ht_1 are supposed to int. Anyway, can  you type cast these to variables to int and then resize - that must work.

**Comment by Dangwanli** [comment]
Thank you very much. I have solved this problem.
