### ISSUE TITLE
test.py : Error

### ISSUE THREAD

**Issue by Tikam02** [svishwa/crowdcount-mcnn#28]
/ML/Crowd-count/crowdcount-mcnn$ python3 test.py
Pre-loading the data. This may take a while...
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    data_loader = ImageDataLoader(data_path, gt_path, shuffle=False, gt_downsample=True, pre_load=True)
  File "/home/tikam/ML/Crowd-count/crowdcount-mcnn/src/data_loader.py", line 35, in __init__
    img = cv2.resize(img,(wd_1,ht_1))
TypeError: integer argument expected, got float

**Comment by xushengim** [comment]
I mit the same problem.
There are some differences between python 2.x and python 3.x .
change / into // to get the int wd_1 and ht_1 in test.py.
