### ISSUE TITLE
Is your test model trained by yourself?

### ISSUE THREAD

**Issue by SelinaFelton** [svishwa/crowdcount-mcnn#3]
I'm confused about what wrong with the code, I just use your code to train my model, and select the model which has lowest MAE and MSE as test model, but when I test my mode, I gets higher MAE(195.83) and MSE(265.86) than you provide

**Comment by SelinaFelton** [comment]
I also download your model, part_A has MAE:342.76 MSE:489.01, part_B has MAE:108.30 MSE:150.75, I only change codes where use cv2, I load my data by using PIL

**Comment by svishwa** [comment]
I verified test code with PIL image reader and I am getting good results (similar to the paper). 

What is the range of values after loading the image? Is it [0,255] or [0,1]. If I force my pixel values to be between [0,1], then I am getting a high MAE/MSE that is similar to what you quoted.

**Comment by SelinaFelton** [comment]
My range of PIL img is [0，255], there may be something wrong about resizing density map. If I want to replace all functions in cv2 by using PIL and numpy, what should I write to replace the codes which can change density map's size?
There is what I have changed, but it doesn't work well.

`               img_t = Image.open(os.path.join(self.data_path,fname)).convert('L')
                wd, ht = img_t.size
                ht_1 = (ht/4)*4
                wd_1 = (wd/4)*4
                img.resize((wd_1,ht_1))
                img = np.array(img_t,dtype=np.uint8)
                img = img.astype(np.float32, copy=False)
                img = img.reshape((1,1,img.shape[0],img.shape[1]))
                
                den_t = pd.read_csv(os.path.join(self.gt_path,os.path.splitext(fname)[0] + '.csv'), sep=',',header=None).as_matrix()                        
                den_img = Image.fromarray(den_t)
                if self.gt_downsample:
                    wd_1 = wd_1/4
                    ht_1 = ht_1/4
                    den_img.resize(wd_1,ht_1)
                    den = np.array(den_img, dtype = np.uint8)                
                    den = den * ((wd*ht)/(wd_1*ht_1))
                else:
                    den_img.resize(wd_1,ht_1)
                    den = np.array(den_img, dtype = np.uint8)
                    den = den * ((wd*ht)/(wd_1*ht_1))
                    
                den  = den_t.astype(np.float32, copy=False)
                den = den.reshape((1,1,den.shape[0],den.shape[1]))`

**Comment by SelinaFelton** [comment]
My range of PIL img is [0，255], there may be something wrong about resizing density map. If I want to replace all functions in cv2 by using PIL and numpy, what should I write to replace the codes which can change density map's size?
There is what I have written, but it doesn't work well.

[https://paste.ubuntu.com/25717601/](url)

**Comment by svishwa** [comment]
Your code snippet looks fine (except for den_img.resize(wd_1,ht_1) which has to be den_img.resize((wd_1,ht_1)). I tried with your changes on my side and it works perfectly. I am not sure what is wrong. You may want to visualize the ground truth and estimated density map by setting vis=True (uses opencv function!).

**Comment by SelinaFelton** [comment]
I have found the bug of my code, I have forgotten to change the code in utils.py, in this file I used the numpy.resize method.
Now it work perfectly. Tkanks for your help.
