### ISSUE TITLE
UC_FF_50 dataset pre-processing

### ISSUE THREAD

**Issue by asif07hossain** [svishwa/crowdcount-mcnn#7]
Dear svishwa, I am not getting shanghatitech images publicly. I also emailed to the authors but yet I dint get any kind of links of the dataset. I have UCF dataset. Can you please provide me the UC_FF_50 data processing marlab codes, if available?

**Comment by guohaoyu110** [comment]
glad to send you the shanghaitech dataset http://pan.baidu.com/s/1c1Qj1Gc

**Comment by asif07hossain** [comment]
I have sent email to authors, but still I am not getting the dataset. Is it possible to give me the dataset. I am waiting for the dataset so I can run your code. Thank you very much in advance. Can you please provide me with that dataset?

**Comment by asif07hossain** [comment]
Thanks a lot for your kindly help... I got it :)
